# Generated by Django 3.1.3 on 2022-02-10 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_no',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course'),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.FloatField(),
        ),
    ]
